version: "3.9"

services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_SCHEMA=public
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=12345
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990
    depends_on:
      - postgres

# Connects to pre-existing network
networks:
  default:
    external: true
    name: postgres_default
