version: '3.9'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    restart: unless-stopped
    ports:
      - 8891:8891
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_management load_definitions /tmp/rabbitmq.definitions.json'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'status']
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/imex/rabbitmq.definitions.all.json:/tmp/rabbitmq.definitions.json:ro
      - ./.data/rabbitmq:/var/lib/rabbitmq
