version: "3"
services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=12345MSSql@
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
