version: '3.9'

services:
  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    networks:
      - mysql_default
    ports:
      - '8888:80'
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 12345
      WORDPRESS_DB_NAME: wordpressdb
    volumes: ['./:/var/www/html']
networks:
  mysql_default:
    external: true
