version: '3.9'

services:
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./.data/redis:/data
    command:
      [
        'redis-server',
        '--save',
        '900 1',
        '--save',
        '300 10',
        '--save',
        '60 10000'
      ]

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    restart: unless-stopped
    ports:
      - 5540:5540
    volumes:
      - ./.data/redis-insight:/data
    depends_on:
      - redis
